### ISSUE TITLE
Having problems in runing it shows error 

### ISSUE THREAD

**Issue by gr8laarab** [agusmakmun/setor#2]
Traceback (most recent call last):
  File "blog-view.py", line 34, in <module>
	with TorRequest() as tr:
  File "/usr/local/lib/python2.7/dist-packages/torrequest.py", line 21, in __init__
	self._tor_proc = self._launch_tor()
  File "/usr/local/lib/python2.7/dist-packages/torrequest.py", line 46, in _launch_tor
	take_ownership=True)
  File "/usr/local/lib/python2.7/dist-packages/stem/process.py", line 285, in launch_tor_with_config
	return launch_tor(tor_cmd, args, torrc_path, completion_percent, init_msg_handler, timeout, take_ownership)
  File "/usr/local/lib/python2.7/dist-packages/stem/process.py", line 98, in launch_tor
	raise OSError("'%s' isn't available on your system. Maybe it's not in your PATH?" % tor_cmd)
OSError: 'tor' isn't available on your system. Maybe it's not in your PATH?

Plss help me out my email id is laarab123parwez@gmail.com.

**Comment by harm0nic** [comment]
@gr8laarab run with sudo/admin access
